[package]
name = "aurders"
version = "1.0.0"
description = "A simple AUR helper for developer to publish their projects easily on Arch User Repository."
readme = "README.md"
license = "MIT"
authors = ["Mitesh <smiteshhc@gmail.com>"]
edition = "2021"

[dependencies]
clap = "4.5.20"
sha256 = "1.5.0"
tar = "0.4.42"
flate2 = "1.0.34"
